# Site settings
title: hankniel
baseurl: ""
url: "https://hankniel.github.io"
google_analytics: G-6PPHKRGJGV # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Dao Duy Dai
  desc: 
  email: aiaoduy@gmail.com
  selfie: assets/img/profile.png

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: hankniel
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/daoduydai/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
  - "screenshot.png"
